"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { Icon } from "@/components/common/Icon";
import { getCurrentUser, type AuthUser } from "@/lib/authApi";
import { createCommunityPost, getCommunityPost, resolveCommunityImageUrl, updateCommunityPost, type CommunityCategory } from "@/lib/communityApi";
import { CommunityPlaceSearch, type CommunityPlace } from "./CommunityPlaceSearch";
import styles from "./Community.module.css";

export function CommunityEditor({ postId }: { postId?: string }) {
  const router = useRouter(); const imageInput = useRef<HTMLInputElement>(null); const [user, setUser] = useState<AuthUser | null>(null); const [authReady, setAuthReady] = useState(false); const [category, setCategory] = useState<CommunityCategory>("FIELD_STORY"); const [placeText, setPlaceText] = useState(""); const [place, setPlace] = useState<CommunityPlace | null>(null); const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [notice, setNotice] = useState(false); const [image, setImage] = useState<File | null>(null); const [existingImage, setExistingImage] = useState<string | null>(null); const [removeImage, setRemoveImage] = useState(false); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  useEffect(() => { let active = true; void getCurrentUser().then((current) => active && setUser(current)).catch(() => active && setUser(null)).finally(() => active && setAuthReady(true)); return () => { active = false; }; }, []);
  useEffect(() => { if (!postId) return; const controller = new AbortController(); void getCommunityPost(postId, controller.signal).then((post) => { setCategory(post.category); setPlaceText(post.place_name || ""); setPlace(post.latitude != null && post.longitude != null ? { placeName: post.place_name || post.address || "선택 위치", address: post.address || post.place_name || "", latitude: post.latitude, longitude: post.longitude } : null); setTitle(post.title); setContent(post.content); setNotice(post.is_notice); setExistingImage(post.image_url); }).catch(() => setError("게시글을 불러오지 못했어요.")); return () => controller.abort(); }, [postId]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!title.trim() || !content.trim()) { setError("제목과 내용을 입력해 주세요."); return; } if (!user) { router.push(`/login?next=${encodeURIComponent(postId ? `/community/${postId}/edit` : "/community/new")}`); return; } if (image && image.size > 5 * 1024 * 1024) { setError("사진은 5MB 이하만 첨부할 수 있어요."); return; } setPending(true); setError(""); try { const payload = { category, title: title.trim(), content: content.trim(), place_name: place?.placeName, address: place?.roadAddress || place?.address, latitude: place?.latitude, longitude: place?.longitude, is_notice: user.role === "ADMIN" && notice, image: image || undefined, remove_image: removeImage }; const result = postId ? await updateCommunityPost(postId, payload) : await createCommunityPost(payload); router.replace(`/community/${result.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "게시글을 저장하지 못했어요."); } finally { setPending(false); } };
  if (!authReady) return <main className={styles.editorPage}><div className={styles.editorLoading}>작성 화면을 준비하고 있어요.</div></main>;
  if (!user) return <main className={styles.editorPage}><div className={styles.authState}><Icon name="user" size={28}/><h1>로그인 후 이야기를 작성할 수 있어요.</h1><Link className="button button-primary" href={`/login?next=${encodeURIComponent("/community/new")}`}>로그인하기</Link><Link href="/community">커뮤니티로 돌아가기</Link></div></main>;
  return <main className={styles.editorPage}><header><p>COMMUNITY POST</p><h1>{postId ? "이야기를 다듬어주세요" : "이야기를 나눠주세요"}</h1><span>지역에서 본 변화와 궁금한 점, FlowLink 이용 경험을 공유해 주세요.</span></header><div className={styles.lostGuide}><div><strong>물건을 찾고 계신가요?</strong><span>분실 신고를 등록하면 발견물과 자동으로 비교할 수 있어요.</span></div><Link href="/lost-reports/new">분실 신고하기 <Icon name="arrow" size={14}/></Link></div><form onSubmit={submit} className={styles.editorForm}>
    <section><div className={styles.step}><span>01</span><div><h2>어떤 이야기인가요?</h2><p>분실 신고 대신 지역에서 나누고 싶은 이야기 유형을 골라주세요.</p></div></div><div className={styles.editorCategories}>{[["FIELD_STORY","현장 이야기","지역에서 직접 본 변화"],["QUESTION","궁금해요","지역이나 FlowLink에 관한 질문"],["EXPERIENCE","이용 경험","발견과 반환 과정의 경험"]].map(([value,label,description]) => <button type="button" key={value} aria-pressed={category === value} onClick={() => setCategory(value as CommunityCategory)}><Icon name={value === "FIELD_STORY" ? "location" : value === "QUESTION" ? "info" : "spark"} size={19}/><span><strong>{label}</strong><small>{description}</small></span></button>)}</div>{user.role === "ADMIN" && <label className={styles.noticeToggle}><input type="checkbox" checked={notice} onChange={(event) => setNotice(event.target.checked)}/><span>FLOWLINK NOTICE로 게시</span></label>}</section>
    <section><div className={styles.step}><span>02</span><div><h2>어디에 관한 이야기인가요? <i>선택</i></h2><p>장소를 선택하면 지역 피드와 지도에서 함께 확인할 수 있어요.</p></div></div><CommunityPlaceSearch value={placeText} optional onChange={setPlaceText} onSelect={setPlace}/></section>
    <section><div className={styles.step}><span>03</span><div><h2>어떤 이야기를 나누고 싶나요?</h2><p>다른 사용자가 이해하기 쉽게 구체적으로 적어주세요.</p></div></div><label className={styles.editorField}><span>제목</span><input value={title} maxLength={120} onChange={(event) => setTitle(event.target.value)} placeholder="제목을 입력해 주세요" required/></label><label className={styles.editorField}><span>내용</span><textarea value={content} maxLength={10000} rows={8} onChange={(event) => setContent(event.target.value)} placeholder="지역에서 본 정보나 궁금한 내용을 나눠주세요" required/><small>{content.length} / 10,000</small></label></section>
    <section><div className={styles.step}><span>04</span><div><h2>사진을 함께 보여줄까요? <i>선택</i></h2><p>JPEG, PNG, WebP · 최대 5MB · 1장</p></div></div><input ref={imageInput} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => { const file = event.target.files?.[0] || null; setImage(file); setRemoveImage(false); }}/>{(image || (existingImage && !removeImage)) ? <div className={styles.imagePreview}><img src={image ? URL.createObjectURL(image) : resolveCommunityImageUrl(existingImage) || undefined} alt="첨부 이미지 미리보기"/><button type="button" aria-label="첨부 이미지 삭제" onClick={() => { setImage(null); setRemoveImage(true); if (imageInput.current) imageInput.current.value = ""; }}><Icon name="close" size={17}/></button></div> : <button className={styles.imageAdd} type="button" onClick={() => imageInput.current?.click()}><Icon name="camera" size={20}/>사진 추가</button>}</section>
    {error && <p className={styles.formError} role="alert">{error}</p>}<footer><Link className="button button-secondary" href={postId ? `/community/${postId}` : "/community"}>취소</Link><button className="button button-primary" type="submit" disabled={pending}>{pending ? "저장하는 중..." : postId ? "수정하기" : "게시하기"}</button></footer>
  </form></main>;
}
