"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { Icon } from "@/components/common/Icon";
import { getCurrentUser, type AuthUser } from "@/lib/authApi";
import { createCommunityComment, deleteCommunityComment, deleteCommunityPost, getCommunityPost, listCommunityComments, resolveCommunityImageUrl, type CommunityComment, type CommunityPost } from "@/lib/communityApi";
import styles from "./Community.module.css";
const labels = { FIELD_STORY: "현장 이야기", QUESTION: "궁금해요", EXPERIENCE: "이용 경험" };
export function CommunityDetail({ postId }: { postId: string }) {
  const router = useRouter(); const menuRef = useRef<HTMLDivElement>(null); const deleteTrigger = useRef<HTMLButtonElement>(null); const [post, setPost] = useState<CommunityPost | null>(null); const [comments, setComments] = useState<CommunityComment[]>([]); const [user, setUser] = useState<AuthUser | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [menu, setMenu] = useState(false); const [confirm, setConfirm] = useState(false); const [content, setContent] = useState(""); const [pending, setPending] = useState(false);
  useEffect(() => { const controller = new AbortController(); void Promise.all([getCommunityPost(postId, controller.signal), listCommunityComments(postId, controller.signal)]).then(([postData, commentData]) => { setPost(postData); setComments(commentData); }).catch(() => setError("게시글을 불러오지 못했어요.")).finally(() => setLoading(false)); return () => controller.abort(); }, [postId]); useEffect(() => { void getCurrentUser().then(setUser).catch(() => setUser(null)); }, []);
  useEffect(() => { if (!confirm) return; const escape = (event: KeyboardEvent) => { if (event.key === "Escape") { setConfirm(false); deleteTrigger.current?.focus(); } }; window.addEventListener("keydown", escape); return () => window.removeEventListener("keydown", escape); }, [confirm]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!user) { router.push(`/login?next=/community/${postId}`); return; } if (!content.trim() || pending) return; setPending(true); try { const item = await createCommunityComment(postId, content.trim()); setComments((current) => [...current, item]); setContent(""); setPost((current) => current ? { ...current, comment_count: current.comment_count + 1 } : current); } catch (cause) { setError(cause instanceof Error ? cause.message : "댓글을 등록하지 못했어요."); } finally { setPending(false); } };
  if (loading) return <main className={styles.detailPage}><div className={styles.detailLoading}>이야기를 불러오고 있어요.</div></main>;
  if (!post) return <main className={styles.detailPage}><div className={styles.state}><h1>{error || "게시글을 찾을 수 없어요."}</h1><Link href="/community">커뮤니티로 돌아가기</Link></div></main>;
  const canEdit = user?.id === post.user_id; const canDelete = canEdit || user?.role === "ADMIN";
  return <main className={styles.detailPage}><Link className={styles.backLink} href="/community"><Icon name="arrow" size={15}/>커뮤니티</Link><article className={styles.detailArticle}><header><div><span>{post.is_notice ? "FLOWLINK NOTICE" : "USER STORY"}</span><em>{labels[post.category]}</em>{post.place_name && <small><Icon name="location" size={13}/>{post.place_name}</small>}</div>{canDelete && <div className={styles.postMenu} ref={menuRef}><button ref={deleteTrigger} type="button" aria-label="게시글 메뉴" aria-expanded={menu} onClick={() => setMenu((value) => !value)}>•••</button>{menu && <div>{canEdit && <Link href={`/community/${post.id}/edit`}>수정</Link>}<button type="button" onClick={() => { setMenu(false); setConfirm(true); }}>삭제</button></div>}</div>}</header><h1>{post.title}</h1><p className={styles.meta}>{post.nickname} · {new Date(post.created_at).toLocaleString("ko-KR")}</p><div className={styles.body}>{post.content}</div>{post.image_url && <img className={styles.detailImage} src={resolveCommunityImageUrl(post.image_url) || ""} alt="게시글 첨부 이미지"/>}</article><section className={styles.comments}><header><h2>댓글 <span>{comments.length}</span></h2></header><form onSubmit={submit}><input value={content} maxLength={1000} onChange={(event) => setContent(event.target.value)} placeholder={user ? "댓글을 입력해 주세요..." : "로그인 후 댓글을 작성할 수 있어요"} aria-label="댓글 내용"/><button type="submit" disabled={pending || !content.trim()}>{pending ? "등록 중" : "등록"}</button></form>{error && <p className={styles.commentError} role="alert">{error}</p>}<div>{comments.length ? comments.map((comment) => <article key={comment.id}><div><strong>{comment.nickname}</strong><span>{new Date(comment.created_at).toLocaleString("ko-KR")}</span></div><p>{comment.content}</p>{(user?.id === comment.user_id || user?.role === "ADMIN") && <button type="button" onClick={() => void deleteCommunityComment(comment.id).then(() => setComments((current) => current.filter((item) => item.id !== comment.id))).catch(() => setError("댓글을 삭제하지 못했어요."))}>삭제</button>}</article>) : <p className={styles.noComments}>아직 댓글이 없어요. 첫 댓글을 남겨보세요.</p>}</div></section>{confirm && <div className={styles.deleteBackdrop} onMouseDown={(event) => event.target === event.currentTarget && setConfirm(false)}><section role="alertdialog" aria-modal="true" aria-labelledby="delete-post-title"><h2 id="delete-post-title">게시글을 삭제할까요?</h2><p>삭제한 글은 다시 확인하기 어려울 수 있어요.</p><div><button className="button button-secondary" type="button" onClick={() => setConfirm(false)}>취소</button><button className="button button-primary" type="button" onClick={() => void deleteCommunityPost(post.id).then(() => router.replace("/community")).catch(() => setError("게시글을 삭제하지 못했어요."))}>삭제</button></div></section></div>}</main>;
}
