"use client";

import Link from "next/link";
import Image from "next/image";
import { useEffect, useMemo, useState, type CSSProperties } from "react";
import { Icon } from "@/components/common/Icon";
import { getAdminDashboard, resolveAdminDashboardImageUrl, type AdminDashboardData } from "@/lib/adminDashboardApi";
import { listAdminOwnershipClaims, type AdminOwnershipClaim } from "@/lib/adminOwnershipClaimsApi";
import styles from "./AdminDashboardClient.module.css";

type Period = "today" | "7d" | "all";
const time = new Intl.DateTimeFormat("ko-KR", { hour: "2-digit", minute: "2-digit" });
const statusLabel: Record<string, string> = { DETECTED: "탐지됨", RECOVERED: "확인된 발견물", AVAILABLE: "보관 중", CLAIM_PENDING: "소유자 확인 중", RETURNED: "반환 완료", APPROVED: "승인", REJECTED: "거절" };
const actionLabel: Record<string, string> = { OWNERSHIP_CLAIM_CREATED: "소유권 확인 요청", OWNERSHIP_CLAIM_REVIEWED: "소유권 확인 검토", DETECTED_OBJECT_REVIEWED: "AI 탐지 객체 검토", FOUND_ITEM_UPDATED: "공식 발견물 수정" };
const periodLabel: Record<Period, string> = { today: "오늘", "7d": "최근 7일", all: "전체" };

function elapsed(value?: string | null) { if (!value) return "처리 대기"; const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000)); return minutes >= 60 ? `${Math.floor(minutes / 60)}시간 대기` : `${minutes}분 대기`; }

export function AdminDashboardClient() {
  const [analytics, setAnalytics] = useState<AdminDashboardData | null>(null);
  const [period, setPeriod] = useState<Period>("today");
  const [claims, setClaims] = useState<AdminOwnershipClaim[]>([]);
  const [errors, setErrors] = useState<string[]>([]);
  const [analyticsLoading, setAnalyticsLoading] = useState(false);

  useEffect(() => { const controller = new AbortController(); Promise.allSettled([getAdminDashboard("today", controller.signal), listAdminOwnershipClaims(controller.signal)]).then(([dashboardResult, claimResult]) => { if (controller.signal.aborted) return; const nextErrors: string[] = []; if (dashboardResult.status === "fulfilled") setAnalytics(dashboardResult.value); else nextErrors.push("dashboard"); if (claimResult.status === "fulfilled") setClaims(claimResult.value); else nextErrors.push("claims"); setErrors(nextErrors); }); return () => controller.abort(); }, []);
  const changePeriod = async (next: Period) => { setPeriod(next); setAnalyticsLoading(true); try { setAnalytics(await getAdminDashboard(next)); setErrors((value) => value.filter((name) => name !== "analytics")); } catch { setErrors((value) => [...value.filter((name) => name !== "analytics"), "analytics"]); } finally { setAnalyticsLoading(false); } };

  const pendingClaims = useMemo(() => claims.filter((claim) => claim.status === "PENDING").slice(0, 3), [claims]);
  const returnClaims = useMemo(() => claims.filter((claim) => claim.status === "APPROVED").slice(0, 2), [claims]);
  const waiting = pendingClaims.length + returnClaims.length;
  const metrics = analytics?.metrics;
  const stats = analytics?.metrics;
  const signal = waiting ? { label: "처리 대기", text: `소유권 확인 관련 업무 ${waiting}건이 처리 대기 중입니다.` } : { label: "운영 정상", text: "현재 지연된 주요 업무가 없습니다." };

  return <main className={styles.page}>
    <header className={styles.intro}><p>ADMIN FLOW</p><h1>관리자 대시보드</h1><span>오늘의 발견부터 매칭과 반환까지 운영 흐름을 확인하세요.</span></header>

    <section className={styles.summary} aria-labelledby="admin-summary-title"><div className={styles.sectionHeading}><div><p>NOW</p><h2 id="admin-summary-title">현재 운영 상황</h2></div><span className={waiting ? styles.signalAttention : styles.signalNormal}><i />{signal.label}</span></div>
      {!analytics ? errors.includes("dashboard") ? <State text="운영 요약을 불러오지 못했습니다." error /> : <Skeleton /> : <><p className={styles.summarySentence}>{signal.text}</p><dl className={styles.metricStrip}><div><dt>발견</dt><dd>{metrics?.discovered}</dd></div><div><dt>자동 매칭</dt><dd>{metrics?.matched}</dd></div><div><dt>처리 대기</dt><dd>{waiting}</dd></div><div><dt>반환 완료</dt><dd>{metrics?.returned}</dd></div></dl></>}
    </section>

    <div className={styles.twoColumn}><section className={styles.panel} aria-labelledby="priority-title"><Heading eyebrow="ACTION" title="오늘의 우선 처리" id="priority-title" />
      {errors.includes("claims") ? <State text="소유권 요청을 불러오지 못했습니다." error /> : waiting === 0 ? <State text="현재 확인이 필요한 업무가 없습니다." /> : <div className={styles.priorityList}>{pendingClaims.map((claim, index) => <Priority key={claim.id} index={index + 1} label="소유권 확인 요청" title={`${claim.found_item.color ?? ""} ${claim.found_item.item_category_name}`.trim()} detail={claim.found_item.area_name} meta={elapsed(claim.created_at)} href="/admin/ownership-claims" action="확인하기" />)}{returnClaims.map((claim, index) => <Priority key={claim.id} index={pendingClaims.length + index + 1} label="반환 처리 대기" title={claim.found_item.public_description || claim.found_item.item_category_name} detail="소유권 승인 완료" meta={elapsed(claim.updated_at)} href="/admin/ownership-claims" action="처리하기" />)}</div>}
    </section><section className={styles.panel} aria-labelledby="recent-title"><Heading eyebrow="DISCOVERY" title="최근 발견" id="recent-title" href="/found-items" action="발견물 관리" />{!analytics ? <Skeleton /> : analytics.recent_items.length ? <div className={styles.recentList}>{analytics.recent_items.map((item) => <Link href={`/found-items/${item.id}`} key={item.id}><DetectionThumbnail imageUrl={item.image_url} label={`${item.item_category_name} 발견물 이미지`} /><div><strong>{item.public_description || `${item.color ?? ""} ${item.item_category_name}`}</strong><span>{time.format(new Date(item.found_at))} · {item.area_name}</span></div><b>{statusLabel[item.status] ?? item.status}</b><Icon name="arrow" size={14} /></Link>)}</div> : <State text="선택한 기간에 등록된 공식 발견물이 없습니다." />}</section></div>

    <section className={styles.analyticsHead}><div><p>ANALYTICS</p><h2>운영 통계</h2></div><div className={styles.periods} role="group" aria-label="통계 기간">{(["today", "7d", "all"] as Period[]).map((value) => <button type="button" aria-pressed={period === value} onClick={() => void changePeriod(value)} key={value}>{periodLabel[value]}</button>)}</div></section>
    {errors.includes("analytics") ? <State text="선택한 기간의 통계를 불러오지 못했습니다." error /> : analyticsLoading || !analytics ? <Skeleton /> : <>
      <div className={styles.chartGrid}><section className={styles.panel}><Heading eyebrow="TREND" title="운영 추세" /><LineChart data={analytics.trend} /></section><section className={styles.panel}><Heading eyebrow="CLAIMS" title="소유권 요청 상태" /><ClaimDonut data={analytics.claim_status_counts} /></section></div>
      <div className={styles.chartGrid}><section className={styles.panel}><Heading eyebrow="AI DETECTION" title={`AI 탐지 현황${analytics.average_confidence == null ? "" : ` · 평균 ${Math.round(analytics.average_confidence * 100)}%`}`} />{analytics.category_counts.length ? <Bars data={analytics.category_counts} /> : <State text="선택한 기간에 AI 탐지 데이터가 없습니다." />}</section><section className={styles.panel}><Heading eyebrow="EVIDENCE" title="최근 AI 탐지" href="/admin/detections" action="전체 검토" />{analytics.recent_detections.length ? <div className={styles.recentList}>{analytics.recent_detections.map((item) => <Link href={`/admin/detections?detection=${item.detection_event_id}`} key={item.id}><DetectionThumbnail imageUrl={item.image_url} label={`${item.item_category_name} 탐지 이미지`} /><div><strong>{item.item_category_name}</strong><span>{Math.round(item.confidence * 100)}% · {time.format(new Date(item.detected_at))}</span></div><b>{item.processing_status}</b><Icon name="arrow" size={14} /></Link>)}</div> : <State text="선택한 기간에 최근 AI 탐지가 없습니다." />}</section></div>
      <Conversion metrics={stats} pendingClaims={pendingClaims.length} />
      <CitizenStats metrics={stats} />
    </>}

    <section className={styles.history} aria-labelledby="history-title"><Heading eyebrow="OPERATIONS" title="최근 운영 기록" id="history-title" />{!analytics ? <Skeleton /> : analytics.recent_history.length ? <div>{analytics.recent_history.map((record) => <div key={record.id}><time>{time.format(new Date(record.created_at))}</time><strong>{record.entity_type} #{record.entity_id}</strong><span>{actionLabel[record.action_type] ?? record.action_type}</span><b>{record.new_status ? statusLabel[record.new_status] ?? record.new_status : "처리 기록"}</b></div>)}</div> : <State text="선택한 기간에 처리된 운영 기록이 없습니다." />}</section>
  </main>;
}

function Heading({ eyebrow, title, id, href, action }: { eyebrow: string; title: string; id?: string; href?: string; action?: string }) { return <div className={styles.sectionHeading}><div><p>{eyebrow}</p><h2 id={id}>{title}</h2></div>{href && <Link href={href}>{action} <Icon name="arrow" size={14} /></Link>}</div>; }
function DetectionThumbnail({ imageUrl, label }: { imageUrl?: string | null; label: string }) { const resolved = resolveAdminDashboardImageUrl(imageUrl); const [failedUrl, setFailedUrl] = useState<string | null>(null); return <span className={styles.thumb}>{resolved && failedUrl !== resolved ? <Image className={styles.detectImage} src={resolved} alt={label} width={52} height={52} unoptimized onError={() => setFailedUrl(resolved)} /> : <Icon name="scan" size={20} />}</span>; }
function Priority({ index, label, title, detail, meta, href, action }: { index: number; label: string; title: string; detail: string; meta: string; href: string; action: string }) { return <div className={styles.priority}><i>{String(index).padStart(2, "0")}</i><div><span>{label}</span><strong>{title}</strong><small>{detail} · {meta}</small></div><Link href={href}>{action} <Icon name="arrow" size={15} /></Link></div>; }
function Bars({ data }: { data: AdminDashboardData["category_counts"] }) { const max = Math.max(1, ...data.map((item) => item.count)); return <div className={styles.bars}>{data.map((item) => <div key={item.code}><span>{item.name}</span><i><b style={{ width: `${(item.count / max) * 100}%` }} /></i><strong>{item.count}</strong></div>)}</div>; }
function LineChart({ data }: { data: AdminDashboardData["trend"] }) { const keys = ["discovered", "matched", "returned"] as const; const labels = { discovered: "발견", matched: "자동 매칭", returned: "반환 완료" }; const max = Math.max(1, ...data.flatMap((point) => keys.map((key) => point[key]))); const x = (index: number) => data.length === 1 ? 50 : index / (data.length - 1) * 100; const y = (value: number) => 92 - value / max * 78; const points = (key: typeof keys[number]) => data.map((point, index) => `${x(index)},${y(point[key])}`).join(" "); if (!data.some((point) => keys.some((key) => point[key]))) return <State text="선택한 기간에 운영 추세 데이터가 없습니다." />; return <div className={styles.lineChart}><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="발견, 자동 매칭, 반환 완료 운영 추세">{keys.map((key) => <g key={key}><polyline className={key === "discovered" ? styles.lineDiscovery : key === "matched" ? styles.lineMatch : styles.lineReturn} points={points(key)} />{data.map((point, index) => <circle key={point.label} cx={x(index)} cy={y(point[key])} r="1.5"><title>{point.label} · {labels[key]} {point[key]}건</title></circle>)}</g>)}</svg><div className={styles.axis}>{data.map((point) => <span key={point.label}>{point.label}</span>)}</div><div className={styles.legend}><span><i />발견</span><span><i />자동 매칭</span><span><i />반환 완료</span></div></div>; }
function ClaimDonut({ data }: { data: AdminDashboardData["claim_status_counts"] }) { const labels: Record<string, string> = { PENDING: "확인 대기", APPROVED: "승인", REJECTED: "거절", RETURNED: "반환 완료" }; const ordered = ["PENDING", "APPROVED", "REJECTED", "RETURNED"].map((status) => ({ status, count: data.find((item) => item.status === status)?.count ?? 0 })); const total = ordered.reduce((sum, item) => sum + item.count, 0); if (!total) return <State text="해당 기간의 소유권 요청이 없습니다." />; let offset = 0; const stops = ordered.map((item, index) => { const start = offset; offset += item.count / total * 100; return `var(--claim-${index}) ${start}% ${offset}%`; }).join(", "); return <div className={styles.donutWrap}><div className={styles.donut} style={{ background: `conic-gradient(${stops})` } as CSSProperties}><span><small>총 요청</small><strong>{total}건</strong></span></div><div className={styles.donutLegend}>{ordered.map((item, index) => <span key={item.status}><i data-tone={index} />{labels[item.status]} <b>{item.count}</b></span>)}</div></div>; }
function Conversion({ metrics, pendingClaims }: { metrics?: AdminDashboardData["metrics"]; pendingClaims: number }) { const values = [metrics?.ai_detections ?? 0, metrics?.official_found_items ?? 0, metrics?.matched ?? 0, metrics?.claims ?? 0, metrics?.returned ?? 0]; const labels = ["AI 탐지", "공식 발견물", "자동 매칭", "소유권 확인", "반환 완료"]; return <section className={styles.flowPanel}><Heading eyebrow="CONVERSION" title="발견부터 반환까지" /><ol className={styles.flow}>{labels.map((label, index) => <li key={label}><i>{index + 1}</i><span>{label}</span><strong>{values[index]}</strong></li>)}</ol><p className={styles.insight}>{pendingClaims ? `소유권 확인 요청 ${pendingClaims}건이 처리 대기 중입니다.` : "현재 주요 처리 단계에 지연된 업무가 없습니다."}</p></section>; }
function CitizenStats({ metrics }: { metrics?: AdminDashboardData["metrics"] }) { const values = [metrics?.citizen_reports ?? 0, metrics?.citizen_pending ?? 0, metrics?.citizen_linked ?? 0, metrics?.citizen_sightings ?? 0]; const labels = ["기간 내 제보", "확인 대기", "공식 발견물 전환", "추가 목격"]; return <section className={styles.flowPanel}><Heading eyebrow="CITIZEN REPORTS" title="시민 제보 현황" href="/admin/citizen-reports" action="제보 검토" /><ol className={styles.flow}>{labels.map((label, index) => <li key={label}><i>{index + 1}</i><span>{label}</span><strong>{values[index]}</strong></li>)}</ol></section>; }
function State({ text, error = false }: { text: string; error?: boolean }) { return <div className={`${styles.state} ${error ? styles.stateError : ""}`}><Icon name={error ? "spark" : "document"} size={20} /><span>{text}</span></div>; }
function Skeleton() { return <div className={styles.skeleton} aria-label="운영 정보를 불러오는 중입니다." role="status" />; }
