"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Icon } from "@/components/common/Icon";
import { adminImageUrl, createFoundItemFromCitizen, getAdminCitizenReport, listAdminCitizenReports, markCitizenReportUnderReview, type AdminCitizenReport } from "@/lib/adminCitizenReportsApi";
import styles from "./AdminCitizenReportsClient.module.css";

const labels: Record<string, string> = { PENDING: "검토 대기", UNDER_REVIEW: "검토 중", LINKED: "공식 발견물 연결", REJECTED: "반려", CANCELLED: "취소" };
const filters = [{ value: "", label: "전체" }, { value: "PENDING", label: "검토 대기" }, { value: "UNDER_REVIEW", label: "검토 중" }, { value: "LINKED", label: "공식 발견물 연결" }];
const date = new Intl.DateTimeFormat("ko-KR", { dateStyle: "medium", timeStyle: "short" });
function format(value: string) { const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? "일시 확인 중" : date.format(parsed); }

function ReportImage({ url, label, compact = false }: { url: string | null; label: string; compact?: boolean }) {
  const source = adminImageUrl(url); const [failedUrl, setFailedUrl] = useState<string | null>(null);
  return <span className={compact ? styles.thumb : styles.heroImage}>{source && failedUrl !== source ? <Image src={source} alt={label} fill sizes={compact ? "64px" : "(max-width: 760px) 100vw, 420px"} unoptimized onError={() => setFailedUrl(source)} /> : <Icon name="fileSearch" size={compact ? 22 : 38} />}</span>;
}

export function AdminCitizenReportsClient() {
  const [reports, setReports] = useState<AdminCitizenReport[]>([]); const [selected, setSelected] = useState<AdminCitizenReport | null>(null);
  const [filter, setFilter] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [processing, setProcessing] = useState(false); const [message, setMessage] = useState(""); const [actionError, setActionError] = useState("");
  const [memo, setMemo] = useState(""); const [storage, setStorage] = useState("");
  const visible = useMemo(() => filter ? reports.filter((report) => report.status === filter) : reports, [filter, reports]);
  useEffect(() => { const controller = new AbortController(); listAdminCitizenReports(undefined, controller.signal).then(setReports).catch(() => setError("시민 제보 목록을 불러오지 못했습니다.")).finally(() => setLoading(false)); return () => controller.abort(); }, []);
  useEffect(() => { if (!selected) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") setSelected(null); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [selected]);
  const open = (report: AdminCitizenReport) => { setSelected(report); setMemo(report.admin_memo ?? ""); setStorage(""); setMessage(""); setActionError(""); const controller = new AbortController(); void getAdminCitizenReport(report.id, controller.signal).then((fresh) => { setSelected((current) => current?.id === fresh.id ? fresh : current); setReports((current) => current.map((item) => item.id === fresh.id ? fresh : item)); setMemo(fresh.admin_memo ?? ""); }).catch(() => setActionError("최신 상세 정보를 불러오지 못했습니다.")); };
  const apply = (updated: AdminCitizenReport, success: string) => { setSelected(updated); setReports((current) => current.map((item) => item.id === updated.id ? updated : item)); setMessage(success); };
  const review = async () => { if (!selected) return; setProcessing(true); setActionError(""); try { apply(await markCitizenReportUnderReview(selected.id, memo), "검토 중 상태로 변경했습니다."); } catch (reason) { setActionError(reason instanceof Error ? reason.message : "상태를 변경하지 못했습니다."); } finally { setProcessing(false); } };
  const resolve = async () => { if (!selected) return; setProcessing(true); setActionError(""); try { apply(await createFoundItemFromCitizen(selected, storage), "공식 발견물로 등록하고 연결했습니다."); } catch (reason) { setActionError(reason instanceof Error ? reason.message : "공식 발견물로 연결하지 못했습니다."); } finally { setProcessing(false); } };

  return <main className={styles.page}><header className={styles.hero}><div><p>ADMIN · CITIZEN REPORTS</p><h1>시민 제보 검토</h1><span>시민이 남긴 발견 정보와 추가 목격을 확인하고 공식 발견물 흐름으로 연결하세요.</span></div><Link href="/admin"><Icon name="arrow" size={16} /> 대시보드로</Link></header>
    <section className={styles.toolbar}><div role="tablist" aria-label="시민 제보 상태 필터">{filters.map((item) => <button type="button" role="tab" aria-selected={filter === item.value} key={item.value || "all"} onClick={() => setFilter(item.value)}>{item.label}<b>{item.value ? reports.filter((report) => report.status === item.value).length : reports.length}</b></button>)}</div></section>
    {loading ? <div className={styles.state} role="status">시민 제보를 불러오는 중입니다.</div> : error ? <div className={`${styles.state} ${styles.error}`} role="alert">{error}<button onClick={() => location.reload()}>다시 시도</button></div> : visible.length === 0 ? <div className={styles.state}>해당 상태의 시민 제보가 없습니다.</div> : <section className={styles.list} aria-label="시민 제보 목록">{visible.map((report) => <button type="button" key={report.id} onClick={() => open(report)}><ReportImage compact url={report.image_url} label={`${report.item_category_name} 대표 이미지`} /><span><strong>{report.color ? `${report.color} ` : ""}{report.item_category_name}</strong><small>{report.area_name} · {format(report.found_at)}</small></span><span><small>작성 {format(report.created_at)}</small><b className={styles[report.status.toLowerCase()]}>{labels[report.status]}</b></span><em>목격 {report.sighting_count}건</em><Icon name="fileSearch" size={19} /></button>)}</section>}
    {selected && <div className={styles.backdrop} onMouseDown={(event) => event.target === event.currentTarget && setSelected(null)}><section className={styles.detail} role="dialog" aria-modal="true" aria-labelledby="citizen-review-title"><button className={styles.close} onClick={() => setSelected(null)} aria-label="시민 제보 상세 닫기"><Icon name="close" size={20} /></button><ReportImage url={selected.image_url} label={`${selected.item_category_name} 시민 제보 이미지`} /><div className={styles.content}><div className={styles.titleRow}><div><p>REPORT #{selected.id}</p><h2 id="citizen-review-title">{selected.color ? `${selected.color} ` : ""}{selected.item_category_name}</h2></div><b className={styles[selected.status.toLowerCase()]}>{labels[selected.status]}</b></div><dl><div><dt>발견 위치</dt><dd>{selected.area_name}</dd></div><div><dt>발견 시간</dt><dd>{format(selected.found_at)}</dd></div><div><dt>제보자</dt><dd>{selected.user_nickname} · 사용자 #{selected.user_id}</dd></div><div><dt>작성 시간</dt><dd>{format(selected.created_at)}</dd></div><div className={styles.wide}><dt>설명</dt><dd>{selected.description}</dd></div></dl>
      <section className={styles.sightings}><h3>추가 목격 이력 <span>{selected.sighting_count}</span></h3>{selected.sightings.length ? selected.sightings.map((item) => <article key={item.id}><ReportImage compact url={item.image_url} label="추가 목격 이미지" /><div><time>{format(item.sighted_at)}</time><strong>{item.location_name}</strong><p>{item.description}</p></div></article>) : <p>추가 목격 정보가 없습니다.</p>}</section>
      {selected.linked_found_item ? <section className={styles.linked}><Icon name="fileSearch" size={22} /><div><strong>공식 발견물 #{selected.linked_found_item.id}</strong><span>현재 상태 · {selected.linked_found_item.status}</span></div><Link href={`/found-items/${selected.linked_found_item.id}`}>발견물 확인 <Icon name="arrow" size={15} /></Link></section> : <section className={styles.actions}><label>관리자 메모<textarea value={memo} onChange={(event) => setMemo(event.target.value)} maxLength={2000} disabled={processing} placeholder="검토 과정에서 필요한 메모를 남겨주세요." /></label>{selected.status === "PENDING" && <button className="button button-secondary" type="button" disabled={processing} onClick={() => void review()}>검토 시작</button>}{selected.status === "UNDER_REVIEW" && <><label>보관 위치 <i>선택</i><input value={storage} onChange={(event) => setStorage(event.target.value)} maxLength={255} disabled={processing} placeholder="예: 관리실 보관함 A-3" /></label><button className="button button-primary" type="button" disabled={processing} onClick={() => void resolve()}><Icon name="fileSearch" size={17} /> 공식 발견물로 등록</button></>}</section>}{message && <p className={styles.success} role="status">{message}</p>}{actionError && <p className={styles.actionError} role="alert">{actionError}</p>}</div></section></div>}
  </main>;
}
