export type CommunityCategory = "FIELD_STORY" | "QUESTION" | "EXPERIENCE" | "OPINION";
export type CommunityPost = { id: number; user_id: number; nickname: string; category: CommunityCategory; title: string; content: string; place_name: string | null; address: string | null; latitude: number | null; longitude: number | null; image_url: string | null; is_notice: boolean; comment_count: number; created_at: string; updated_at: string };
export type CommunityComment = { id: number; parent_comment_id: number | null; user_id: number; nickname: string; content: string; created_at: string };
export type CommunitySystemUpdate = { type: "FOUND_ITEM_UPDATE" | "RETURN_UPDATE"; id: number; title: string; place_name: string; latitude: number | null; longitude: number | null; timestamp: string; href: string | null };
export type CommunityFeed = { posts: CommunityPost[]; system_updates: CommunitySystemUpdate[]; context: { found_items: number; new_stories: number; returns: number }; has_more: boolean };
export type CommunityPostPayload = { category: CommunityCategory; title: string; content: string; place_name?: string; address?: string; latitude?: number; longitude?: number; is_notice?: boolean; image?: File; remove_image?: boolean };

export class CommunityApiError extends Error { constructor(message: string, readonly status?: number) { super(message); this.name = "CommunityApiError"; } }
const baseUrl = () => { const value = process.env.NEXT_PUBLIC_API_BASE_URL?.trim(); if (!value) throw new CommunityApiError("API 서버 주소가 설정되지 않았습니다."); return value.replace(/\/+$/, ""); };
export const resolveCommunityImageUrl = (value: string | null) => value ? new URL(value, `${baseUrl()}/`).toString() : null;
function params(values: Record<string, string | number | undefined>) { const result = new URLSearchParams(); Object.entries(values).forEach(([key, value]) => { if (value !== undefined && String(value).trim()) result.set(key, String(value)); }); return result; }
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${baseUrl()}${path}`, { ...init, credentials: "include" }); if (!response.ok) { let message = "커뮤니티 요청을 처리하지 못했습니다."; try { const data = await response.json() as { detail?: string }; if (data.detail) message = data.detail; } catch {} throw new CommunityApiError(message, response.status); } if (response.status === 204) return undefined as T; return response.json() as Promise<T>; }
function form(payload: CommunityPostPayload) { const data = new FormData(); data.set("category", payload.category); data.set("title", payload.title); data.set("content", payload.content); if (payload.place_name) data.set("place_name", payload.place_name); if (payload.address) data.set("address", payload.address); if (payload.latitude != null) data.set("latitude", String(payload.latitude)); if (payload.longitude != null) data.set("longitude", String(payload.longitude)); data.set("is_notice", String(Boolean(payload.is_notice))); data.set("remove_image", String(Boolean(payload.remove_image))); if (payload.image) data.set("image", payload.image); return data; }
export function getCommunityFeed(filters: { category?: string; query?: string; place?: string; sort?: string; skip?: number; limit?: number }, signal?: AbortSignal) { const query = params(filters).toString(); return request<CommunityFeed>(`/api/community/posts${query ? `?${query}` : ""}`, { signal }); }
export function getCommunityPost(id: string, signal?: AbortSignal) { return request<CommunityPost>(`/api/community/posts/${id}`, { signal }); }
export function createCommunityPost(payload: CommunityPostPayload) { return request<CommunityPost>("/api/community/posts", { method: "POST", body: form(payload) }); }
export function updateCommunityPost(id: string, payload: CommunityPostPayload) { return request<CommunityPost>(`/api/community/posts/${id}`, { method: "PATCH", body: form(payload) }); }
export function deleteCommunityPost(id: number) { return request<void>(`/api/community/posts/${id}`, { method: "DELETE" }); }
export function listCommunityComments(id: string, signal?: AbortSignal) { return request<CommunityComment[]>(`/api/community/posts/${id}/comments`, { signal }); }
export function createCommunityComment(id: string, content: string, parentCommentId?: number) { const data = new FormData(); data.set("content", content); if (parentCommentId) data.set("parent_comment_id", String(parentCommentId)); return request<CommunityComment>(`/api/community/posts/${id}/comments`, { method: "POST", body: data }); }
export function deleteCommunityComment(id: number) { return request<void>(`/api/community/comments/${id}`, { method: "DELETE" }); }
